package br.com.marysplayhaven.model;

public enum Beneficio {
    DESENVOLVIMENTO_DA_AUTONOMIA,
    ESTIMULO_A_CONCENTRACAO,
    DESENVOLVIMENTO_DA_COORDENACAO_MOTORA,
    APRENDIZADO_SENSORIAL,
    ESTIMULO_A_CRIATIVIDADE_E_IMAGINACAO,
    DESENVOLVIMENTO_COGNITIVO,
    DESENVOLVIMENTO_SOCIAL_E_EMOCIONAL,
    MATERIAL_SUSTENTAVEL_E_DURAVEL
}
